# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-09 03:27
from __future__ import unicode_literals

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='input title, max 100', max_length=100, verbose_name='Subject')),
                ('content', models.TextField(verbose_name='Content')),
                ('tag', models.CharField(blank=True, help_text='write tags', max_length=50)),
                ('lnglat', models.CharField(help_text='"longtitude,latitude" type', max_length=30, validators=[blog.models.lnglat_validator])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
