# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-20 12:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20180519_1015'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='ip',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
